// ----------------------------------------------------------------------

export const ROOTS = {
  AUTH: '/auth',
  DASHBOARD: '/dashboard',
  ADMIN: '/admin',
  VENDOR: '/vendor',
  SHOP: '/shop',
  RESTAURANTS: '/restaurants',
  PROFILE: '/profile',
  ROLE: '/role',
  DRIVER: '/driver',
  SERVICE_PROVIDERS: '/service-providers',
  PRODUCTS: '/products',
  BRANDS: '/products/brands',
  UNITS: '/products/units',
  LOCATIONS: '/locations',
  CITY: '/locations/city',
  AREA: '/locations/area',
  CATEGORIES: '/categories',
  CATEGORY_ATTRIBUTES: '/categories/attributes',
  CATEGORY_DETAILS: '/categories/details',
  CATEGORY_EXTRA_DETAILS: '/categories/extra-details',
  SERVICES: '/services',
  // LANGUAGES: '/languages',
  SECTIONS: '/sections',
  PAGE_SECTIONS: '/sections/page-sections',
  PAGES: '/sections/pages',
  NAV_MENU_ITEMS: '/sections/nav-menu-items',
  BANNERS: '/banners',
  COUPONS: '/coupons',
  COMPLAINTS: '/complaints',
  USERS: '/users',
  AFFILIATES: '/affiliates',
  ORDERS: '/orders',
  BASKETS: '/baskets',
  SCHEDULED_BASKETS: '/scheduled-baskets',
  PACKAGES: '/packages',
  SUBSCRIPTIONS: '/subscriptions',
  GIFTS: '/gifts',
  USER_GIFTS: '/user-gifts',
  POINT_EXCHANGES: '/point-exchanges',
  USER_POINTS: '/user-points',
  CURRENCIES: '/currencies',
  RECIPES: '/recipes',
  LEGAL_DOCUMENTS: '/legal-documents',
  FAQS: '/faqs',
  VENDOR_SUBSCRIPTIONS: '/vendor-subscriptions',
  ADMIN_NOTIFICATIONS: '/admin-notifications',
  VENDOR_PACKAGES: '/vendor-packages',
  VENDOR_USERS: '/vendor-users',
  SELLER_REGISTRATIONS: '/seller-registrations',
  STATISTICS: '/statistics',
  REPORTS: '/reports',
  SETTINGS: '/settings',
  CONTACT_METHODS: '/contact-methods',
  BADGES: '/badges',
  ACTIVITY_LOGS: '/activity-logs',
  AFFILIATE_WITHDRAW_REQUESTS: '/affiliate-withdraw-requests',
  AFFILIATE_WALLET_TRANSACTIONS: '/affiliate-wallet-transactions',
  DRIVER_WALLET_TRANSACTIONS: '/driver-wallet-transactions',
  ICONS: '/icons',
  COLORS: '/colors',
  PROMOTIONS: '/promotions',
  COUNTRIES: '/countries',
  SALE_COUNTRIES: '/sale-countries',
  PROMOTION_REQUESTS: '/promotion-requests',
  POINT_RULES: '/point-rules',
  DELIVERY_DISTANCE_RANGES: '/delivery-distance-ranges',
  SCHEDULES: '/schedules',
  USER_BASKET_SCHEDULES: '/user-basket-schedules',
  VENDOR_SERVICE_TYPES: '/vendor-service-types',
  VENDOR_SERVICES: '/vendor-services',
  SHOP_VENDOR_SERVICES: '/shop-vendor-services',
  SERVICE_ORDERS: '/service-orders',
  QUICK_ACTIONS: '/quick-actions',
  POPUP_CAMPAIGNS: '/popup-campaigns',
  FLASH_SALES: '/flash-sales',
  INVENTORY: '/inventory',
  VENDOR_ACCOUNTING: '/vendor-accounting',
  VENDOR_WITHDRAW_REQUESTS: '/vendor-withdraw-requests',
};

// ----------------------------------------------------------------------

export const paths = {
  faqs: '/faqs',
  minimalStore: 'https://mui.com/store/items/minimal-dashboard/',
  // AUTH
  auth: {
    amplify: {
      signIn: `${ROOTS.AUTH}/amplify/sign-in`,
      verify: `${ROOTS.AUTH}/amplify/verify`,
      signUp: `${ROOTS.AUTH}/amplify/sign-up`,
      updatePassword: `${ROOTS.AUTH}/amplify/update-password`,
      resetPassword: `${ROOTS.AUTH}/amplify/reset-password`,
    },
    jwt: {
      signIn: `${ROOTS.AUTH}/jwt/sign-in`,
      signUp: `${ROOTS.AUTH}/jwt/sign-up`,
    },
    firebase: {
      signIn: `${ROOTS.AUTH}/firebase/sign-in`,
      verify: `${ROOTS.AUTH}/firebase/verify`,
      signUp: `${ROOTS.AUTH}/firebase/sign-up`,
      resetPassword: `${ROOTS.AUTH}/firebase/reset-password`,
    },
    auth0: {
      signIn: `${ROOTS.AUTH}/auth0/sign-in`,
    },
    supabase: {
      signIn: `${ROOTS.AUTH}/supabase/sign-in`,
      verify: `${ROOTS.AUTH}/supabase/verify`,
      signUp: `${ROOTS.AUTH}/supabase/sign-up`,
      updatePassword: `${ROOTS.AUTH}/supabase/update-password`,
      resetPassword: `${ROOTS.AUTH}/supabase/reset-password`,
    },
  },
  // DASHBOARD
  dashboard: {
    root: ROOTS.ADMIN,
    vendor: ROOTS.VENDOR,
    shop: ROOTS.SHOP,
    restaurants: ROOTS.RESTAURANTS,
    profile: ROOTS.PROFILE,
    role: ROOTS.ROLE,
    driver: ROOTS.DRIVER,
    serviceProviders: ROOTS.SERVICE_PROVIDERS,
    products: ROOTS.PRODUCTS,
    /** Product CRUD sub-routes under `/products` */
    product: {
      root: ROOTS.PRODUCTS,
      create: `${ROOTS.PRODUCTS}/create`,
      update: (id: string | number) => `${ROOTS.PRODUCTS}/update/${id}`,
      details: (id: string | number) => `${ROOTS.PRODUCTS}/details/${id}`,
    },
    brands: ROOTS.BRANDS,
    brand: {
      root: ROOTS.BRANDS,
      create: `${ROOTS.BRANDS}/create`,
      update: (id: string | number) => `${ROOTS.BRANDS}/update/${id}`,
      details: (id: string | number) => `${ROOTS.BRANDS}/details/${id}`,
    },
    units: ROOTS.UNITS,
    unit: {
      root: ROOTS.UNITS,
      create: `${ROOTS.UNITS}/create`,
      update: (id: string | number) => `${ROOTS.UNITS}/update/${id}`,
    },
    locations: ROOTS.LOCATIONS,
    city: ROOTS.CITY,
    area: ROOTS.AREA,
    categories: ROOTS.CATEGORIES,
    categoryAttributes: ROOTS.CATEGORY_ATTRIBUTES,
    categoryDetails: ROOTS.CATEGORY_DETAILS,
    categoryExtraDetails: ROOTS.CATEGORY_EXTRA_DETAILS,
    services: ROOTS.SERVICES,
    // languages: ROOTS.LANGUAGES,
    sections: ROOTS.SECTIONS,
    pageSections: ROOTS.PAGE_SECTIONS,
    pages: ROOTS.PAGES,
    /** Storefront top-bar items (`nav_menu_items`) */
    navMenuItems: {
      root: ROOTS.NAV_MENU_ITEMS,
      create: `${ROOTS.NAV_MENU_ITEMS}/create`,
      update: (id: string | number) => `${ROOTS.NAV_MENU_ITEMS}/update/${id}`,
    },
    banners: ROOTS.BANNERS,
    coupons: ROOTS.COUPONS,
    complaints: ROOTS.COMPLAINTS,
    users: ROOTS.USERS,
    affiliates: ROOTS.AFFILIATES,
    orders: ROOTS.ORDERS,
    baskets: ROOTS.BASKETS,
    scheduledBaskets: ROOTS.SCHEDULED_BASKETS,
    packages: ROOTS.PACKAGES,
    subscriptions: ROOTS.SUBSCRIPTIONS,
    gifts: ROOTS.GIFTS,
    userGifts: ROOTS.USER_GIFTS,
    pointExchanges: ROOTS.POINT_EXCHANGES,
    userPoints: ROOTS.USER_POINTS,
    currencies: ROOTS.CURRENCIES,
    recipes: ROOTS.RECIPES,
    legalDocuments: ROOTS.LEGAL_DOCUMENTS,
    faqs: ROOTS.FAQS,
    vendorSubscriptions: ROOTS.VENDOR_SUBSCRIPTIONS,
    vendorSubscriptionsCreate: `${ROOTS.VENDOR_SUBSCRIPTIONS}/create`,
    adminNotifications: ROOTS.ADMIN_NOTIFICATIONS,
    vendorPackages: ROOTS.VENDOR_PACKAGES,
    vendorUsers: ROOTS.VENDOR_USERS,
    sellerRegistrations: ROOTS.SELLER_REGISTRATIONS,
    statistics: ROOTS.STATISTICS,
    reports: ROOTS.REPORTS,
    settings: ROOTS.SETTINGS,
    contactMethods: ROOTS.CONTACT_METHODS,
    badges: ROOTS.BADGES,
    activityLogs: ROOTS.ACTIVITY_LOGS,
    affiliateWithdrawRequests: ROOTS.AFFILIATE_WITHDRAW_REQUESTS,
    affiliateWalletTransactions: ROOTS.AFFILIATE_WALLET_TRANSACTIONS,
    driverWalletTransactions: ROOTS.DRIVER_WALLET_TRANSACTIONS,
    icons: ROOTS.ICONS,
    colors: ROOTS.COLORS,
    promotions: ROOTS.PROMOTIONS,
    countries: ROOTS.COUNTRIES,
    saleCountries: ROOTS.SALE_COUNTRIES,
    promotionRequests: ROOTS.PROMOTION_REQUESTS,
    pointRules: ROOTS.POINT_RULES,
    deliveryDistanceRanges: ROOTS.DELIVERY_DISTANCE_RANGES,
    schedules: ROOTS.SCHEDULES,
    userBasketSchedules: ROOTS.USER_BASKET_SCHEDULES,
    userBasketSchedule: {
      root: ROOTS.USER_BASKET_SCHEDULES,
      details: (id: string | number) => `${ROOTS.USER_BASKET_SCHEDULES}/details/${id}`,
    },
    vendorServiceTypes: ROOTS.VENDOR_SERVICE_TYPES,
    vendorServices: ROOTS.VENDOR_SERVICES,
    shopVendorServices: ROOTS.SHOP_VENDOR_SERVICES,
    serviceOrders: ROOTS.SERVICE_ORDERS,
    quickActions: {
      root: ROOTS.QUICK_ACTIONS,
      create: `${ROOTS.QUICK_ACTIONS}/create`,
      update: (id: string | number) => `${ROOTS.QUICK_ACTIONS}/update/${id}`,
    },
    popupCampaigns: {
      root: ROOTS.POPUP_CAMPAIGNS,
      create: `${ROOTS.POPUP_CAMPAIGNS}/create`,
      update: (id: string | number) => `${ROOTS.POPUP_CAMPAIGNS}/update/${id}`,
    },
    flashSales: {
      root: ROOTS.FLASH_SALES,
      create: `${ROOTS.FLASH_SALES}/create`,
      update: (id: string | number) => `${ROOTS.FLASH_SALES}/update/${id}`,
    },
    inventory: ROOTS.INVENTORY,
    vendorAccounting: {
      root: ROOTS.VENDOR_ACCOUNTING,
      /** List + summary live on the index route (no separate /vendors path). */
      vendors: ROOTS.VENDOR_ACCOUNTING,
      vendorDetails: (id: string | number) => `${ROOTS.VENDOR_ACCOUNTING}/vendors/${id}`,
    },
    vendorWithdrawRequests: ROOTS.VENDOR_WITHDRAW_REQUESTS,
  },
};
